FROM cita/cita-run:ubuntu-18.04-20181009

WORKDIR /root/cita

RUN curl -O http://47.104.128.219/cita_sm2_sm3.tar.gz   \
    && tar zxvf cita_sm2_sm3.tar.gz \
    && rm -rf cita_sm2_sm3.tar.gz \
    && cd cita_sm2_sm3

COPY ./docker-entrypoint_sm2.sh ./cita_sm2_sm3
ADD http://47.104.128.219/cita-cli /usr/bin/

WORKDIR /root/cita/cita_sm2_sm3
RUN chmod +x ./docker-entrypoint_sm2.sh \
     && chmod +x /usr/bin/cita-cli
CMD ["./docker-entrypoint_sm2.sh"]


