FROM cita/cita-run:ubuntu-18.04-20180813

WORKDIR /root/cita


ADD https://github.com/cryptape/cita/releases/download/v0.18/cita_secp256k1_sha3.tar.gz  ./ 
RUN tar zxf cita_secp256k1_sha3.tar.gz \
   && cd cita_secp256k1_sha3 

COPY ./docker-entrypoint.sh ./cita_secp256k1_sha3

WORKDIR /root/cita/cita_secp256k1_sha3
RUN chmod +x ./docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]

