FROM cita/cita-run:ubuntu-18.04-20180813

WORKDIR /root/cita

RUN curl -O http://47.104.128.219/cita_ed25519_blake2b.tar.gz   \
    && tar zxvf cita_ed25519_blake2b.tar.gz \
    && rm -rf cita_ed25519_blake2b.tar.gz \
    && cd cita_ed25519_blake2b

COPY ./docker-entrypoint_blake2b.sh ./cita_ed25519_blake2b

WORKDIR /root/cita/cita_ed25519_blake2b
RUN chmod +x ./docker-entrypoint_blake2b.sh
CMD ["./docker-entrypoint_blake2b.sh"]


