name: Build Docker Images

on:
  push:
    branches:
      - master
      - main
      - 'ubuntu-*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:master
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Building docker images"
        run: |
          image="cita/$(basename ${GITHUB_REPOSITORY})"
          tag=${GITHUB_REF#refs/heads/}
          if [ "$tag" = 'master' ] || [ "$tag" = 'main' ]; then
              tag=latest
          fi

          docker buildx build \
              --output "type=image,push=true" \
              --file "Dockerfile" \
              --tag "${image}:${tag}" \
              --platform "linux/amd64" \
              "."

